on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Automerge PR"]
  workflow_dispatch:

env:
  DISTRIBUTOR_ROOT: ""

jobs:
  combine_witness_sigs:
    runs-on: ubuntu-latest
    name: Combine witness signatures
    steps:
    - uses: actions/checkout@v2
    # Attempt to combine witness signatures with the log checkpoint.
    - name: Combine witness signatures
      id: combine_witness_signatures
      uses: google/trillian-examples/serverless/deploy/github/distributor/combine_witness_signatures@HEAD
      with:
          distributor_dir: '${{ env.DISTRIBUTOR_ROOT }}'
          config: 'config.yaml'
    # Update log index.
    - name: Update logs index
      id: update_logs_index
      uses: AlCutter/trillian-examples/serverless/deploy/github/distributor/update_logs_index@update_log_index
      with:
          distributor_dir: '${{ env.DISTRIBUTOR_ROOT }}'
          config: 'config.yaml'
          output: 'logs/README.md'
    # Commit any changes back to distributor repo.
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: Serverless Bot
        commit_user_email: actions@github.com
        commit_author: Serverless Bot <actions@github.com>
        commit_message: Automatically merge witness signatures


